import express from 'express';
import config from '../config.js';
import { all, get, insert, nowIso } from '../db/index.js';
import { randomToken } from '../lib/ids.js';
import { notFound, badRequest } from '../lib/errors.js';
import { authenticate, requireCapability } from '../middleware/auth.js';
import { asyncRoute, download } from '../lib/http.js';
import { query, z, optionalId, optionalText, optionalIsoDate } from '../lib/validate.js';
import { observationFilter, decorate } from '../lib/queries.js';
import { toCsv, toXlsx, streamPdf, attachmentPath } from '../lib/exporters.js';
import { buildAutoSummary } from './inspections.js';

const router = express.Router();

/* -------------------------------------------------------------------------- */
/* Public QR verification - deliberately mounted before the auth guard        */
/* -------------------------------------------------------------------------- */

/**
 * Anyone holding a printed report can scan its QR code and confirm that the
 * document was generated by this system, and that its figures still match.
 */
router.get('/verify/:token', (req, res) => {
  const token = get('SELECT * FROM report_tokens WHERE token = ?', [req.params.token]);
  if (!token) throw notFound('Report');
  const user = token.generated_by ? get('SELECT name, designation FROM users WHERE id = ?', [token.generated_by]) : null;
  const response = {
    verified: true,
    report_type: token.report_type,
    generated_at: token.generated_at,
    generated_by: user ? { name: user.name, designation: user.designation } : null,
  };
  if (token.entity_type === 'inspection') {
    const inspection = get('SELECT * FROM v_inspections i WHERE i.id = ?', [token.entity_id]);
    if (inspection) {
      response.inspection = {
        ref_no: inspection.ref_no,
        type: inspection.inspection_type_name,
        module: inspection.module_name,
        station: inspection.station_name,
        train: inspection.train_number,
        inspector: inspection.inspector_name,
        date: (inspection.started_at ?? inspection.created_at).slice(0, 10),
        status: inspection.status,
        observations: inspection.observation_count,
        open_observations: inspection.open_count,
        closed_observations: inspection.closed_count,
      };
    }
  }
  res.json(response);
});

router.use(authenticate);
router.use(requireCapability('report:read'));

const FORMATS = ['json', 'csv', 'xlsx', 'pdf'];

const filterSchema = z.object({
  format: z.enum(FORMATS).default('json'),
  module_id: optionalId,
  module_code: optionalText,
  station_id: optionalId,
  division_id: optionalId,
  department_id: optionalId,
  supervisor_id: optionalId,
  severity_id: optionalId,
  status: optionalText,
  from: optionalIsoDate,
  to: optionalIsoDate,
  days: z.coerce.number().int().min(1).max(3650).optional(),
  q: optionalText,
  mine: z.coerce.boolean().optional(),
  limit: z.coerce.number().int().min(1).max(5000).default(1000),
});

const OBSERVATION_COLUMNS = [
  { key: 'ref_no', label: 'Observation ID', width: 18 },
  { key: 'module_name', label: 'Module', width: 26 },
  { key: 'inspection_ref', label: 'Inspection', width: 18 },
  { key: 'observed_at', label: 'Date', width: 12, value: (r) => String(r.observed_at).slice(0, 10) },
  { key: 'station_name', label: 'Station', width: 20 },
  { key: 'station_code', label: 'Code', width: 8 },
  { key: 'train_number', label: 'Train', width: 12 },
  { key: 'unit_name', label: 'Unit / Area', width: 20 },
  { key: 'item_name', label: 'Amenity / Item', width: 24 },
  { key: 'category_name', label: 'Category', width: 18 },
  { key: 'observation', label: 'Observation', width: 60 },
  { key: 'severity_name', label: 'Severity', width: 12 },
  { key: 'department_name', label: 'Action by', width: 16 },
  { key: 'supervisor_name', label: 'Concerned supervisor', width: 24 },
  { key: 'supervisor_mobile', label: 'Mobile', width: 14 },
  { key: 'tdc', label: 'TDC', width: 12 },
  { key: 'status', label: 'Status', width: 20, value: (r) => statusLabel(r.status) },
  { key: 'is_overdue', label: 'Overdue', width: 9, value: (r) => (r.is_overdue ? 'Yes' : 'No') },
  { key: 'repeat_count', label: 'Repeated', width: 10 },
  { key: 'inspector_name', label: 'Inspecting officer', width: 22 },
  { key: 'closed_at', label: 'Closed on', width: 12, value: (r) => (r.closed_at ? String(r.closed_at).slice(0, 10) : '') },
];

const STATUS_LABELS = {
  submitted: 'Submitted',
  assigned: 'Assigned',
  acknowledged: 'Acknowledged',
  in_progress: 'Action in progress',
  compliance_submitted: 'Compliance submitted',
  verified: 'Verified',
  closed: 'Closed',
  rejected: 'Rejected',
  reopened: 'Reopened',
  cancelled: 'Cancelled',
};
const statusLabel = (s) => STATUS_LABELS[s] ?? s;

function fetchObservations(filters, user) {
  const { sql, params } = observationFilter(filters, user);
  return all(
    `SELECT * FROM v_observations o WHERE ${sql}
      ORDER BY o.is_overdue DESC, o.severity_rank ASC, o.observed_at DESC LIMIT ?`,
    [...params, filters.limit ?? 1000]
  ).map(decorate);
}

function reportToken(req, { reportType, entityType = null, entityId = null, params = null }) {
  const token = randomToken(12);
  insert('report_tokens', {
    token,
    report_type: reportType,
    entity_type: entityType,
    entity_id: entityId,
    params: params ? JSON.stringify(params) : null,
    generated_by: req.user.id,
  });
  return { token, url: `${config.publicUrl}/api/reports/verify/${token}` };
}

const stamp = () => new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-');

/** Renders one observation list as JSON, CSV, Excel or PDF. */
async function respondWithObservations(req, res, { title, subtitle, filters, meta = [], reportType }) {
  const rows = fetchObservations(filters, req.user);
  const format = filters.format ?? 'json';
  const fileBase = `${reportType}-${stamp()}`;

  if (format === 'json') {
    res.json({ title, subtitle, generated_at: nowIso(), count: rows.length, data: rows });
    return;
  }
  if (format === 'csv') {
    download(res, { fileName: `${fileBase}.csv`, contentType: 'text/csv; charset=utf-8' });
    res.send(toCsv(rows, OBSERVATION_COLUMNS));
    return;
  }
  if (format === 'xlsx') {
    const buffer = await toXlsx([
      { name: 'Observations', title, subtitle, columns: OBSERVATION_COLUMNS, rows },
      {
        name: 'Summary',
        title: 'Summary',
        columns: [
          { key: 'metric', label: 'Metric', width: 30 },
          { key: 'value', label: 'Value', width: 14 },
        ],
        rows: summaryRows(rows),
      },
    ]);
    download(res, {
      fileName: `${fileBase}.xlsx`,
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    res.send(buffer);
    return;
  }

  const verification = reportToken(req, { reportType, params: filters });
  streamPdf(
    res,
    {
      fileName: `${fileBase}.pdf`,
      title,
      subtitle,
      meta: [
        ...meta,
        { label: 'Observations', value: rows.length },
        { label: 'Generated by', value: `${req.user.name}${req.user.designation ? `, ${req.user.designation}` : ''}` },
      ],
      verifyUrl: verification.url,
    },
    (doc, helpers) => {
      helpers.table(
        doc,
        [
          { label: 'ID', key: 'ref_no', width: 0.1 },
          { label: 'Station / Train', width: 0.13, value: (r) => r.location_label },
          { label: 'Unit', key: 'unit_name', width: 0.1 },
          { label: 'Item', key: 'item_name', width: 0.11 },
          { label: 'Observation', key: 'observation', width: 0.26 },
          { label: 'Sev.', key: 'severity_name', width: 0.06 },
          { label: 'Action by', key: 'department_name', width: 0.09 },
          { label: 'TDC', key: 'tdc', width: 0.07 },
          { label: 'Status', width: 0.08, value: (r) => statusLabel(r.status) },
        ],
        rows
      );
      doc.moveDown(0.3);
      doc.font('Helvetica-Bold').fontSize(9).text('Summary');
      doc.font('Helvetica').fontSize(8.5);
      for (const row of summaryRows(rows)) doc.text(`${row.metric}: ${row.value}`);
    }
  );
}

function summaryRows(rows) {
  const open = rows.filter((r) => r.is_open).length;
  const overdue = rows.filter((r) => r.is_overdue).length;
  const closed = rows.filter((r) => r.status === 'closed').length;
  const critical = rows.filter((r) => r.severity_rank === 1).length;
  const repeated = rows.filter((r) => r.repeat_count > 0).length;
  const byDept = {};
  for (const r of rows) byDept[r.department_name] = (byDept[r.department_name] ?? 0) + 1;
  return [
    { metric: 'Total observations', value: rows.length },
    { metric: 'Open', value: open },
    { metric: 'Overdue', value: overdue },
    { metric: 'Closed', value: closed },
    { metric: 'Critical', value: critical },
    { metric: 'Repeated deficiencies', value: repeated },
    ...Object.entries(byDept)
      .sort((a, b) => b[1] - a[1])
      .map(([k, v]) => ({ metric: `Action by ${k}`, value: v })),
  ];
}

/* ------------------------------ report catalogue -------------------------- */

router.get('/catalogue', (_req, res) => {
  res.json({
    formats: FORMATS,
    data: [
      { key: 'inspection', name: 'Inspection Report', path: '/api/reports/inspection/:id', description: 'Full record of one inspection with observations, evidence and signatures' },
      { key: 'compliance', name: 'Compliance Report', path: '/api/reports/compliance', description: 'Action taken, compliance date, verification and closure' },
      { key: 'pending', name: 'Pending Report', path: '/api/reports/pending', description: 'Every observation awaiting compliance' },
      { key: 'overdue', name: 'Overdue Report', path: '/api/reports/overdue', description: 'Observations past their target date of compliance' },
      { key: 'department-wise', name: 'Department-wise Report', path: '/api/reports/department-wise', description: 'Workload and closure performance by department' },
      { key: 'station-wise', name: 'Station-wise Report', path: '/api/reports/station-wise', description: 'Observations, pendency and repeats by station' },
      { key: 'repeated-deficiency', name: 'Repeated Deficiency Report', path: '/api/reports/repeated-deficiency', description: 'Recurring deficiencies with occurrence counts' },
      { key: 'module-wise', name: 'Module-wise Report', path: '/api/reports/module-wise', description: 'Passenger Amenities, Commercial and Safe Running side by side' },
    ],
  });
});

/* ------------------------------ 1. inspection ----------------------------- */

router.get(
  '/inspection/:id',
  query(z.object({ format: z.enum(FORMATS).default('json'), photos: z.coerce.boolean().default(true) })),
  asyncRoute(async (req, res) => {
    const inspection = get('SELECT * FROM v_inspections i WHERE i.id = ?', [req.params.id]);
    if (!inspection) throw notFound('Inspection');
    const observations = all('SELECT * FROM v_observations o WHERE o.inspection_id = ? ORDER BY o.id', [
      inspection.id,
    ]).map(decorate);
    const approvals = all(
      `SELECT * FROM approvals WHERE entity_type = 'inspection' AND entity_id = ? ORDER BY signed_at`,
      [inspection.id]
    );
    const auto = buildAutoSummary(inspection.id);
    const { format } = req.validQuery;
    const place = inspection.station_name
      ? `${inspection.station_name} (${inspection.station_code})`
      : [inspection.train_number, inspection.train_name].filter(Boolean).join(' ') || inspection.section || '-';

    if (format === 'json') {
      res.json({ inspection, observations, approvals, auto_summary: auto });
      return;
    }
    if (format === 'csv') {
      download(res, { fileName: `inspection-${inspection.ref_no}.csv`, contentType: 'text/csv; charset=utf-8' });
      res.send(toCsv(observations, OBSERVATION_COLUMNS));
      return;
    }
    if (format === 'xlsx') {
      const buffer = await toXlsx([
        {
          name: 'Observations',
          title: `${inspection.inspection_type_name} - ${place}`,
          subtitle: `${inspection.ref_no} | ${inspection.inspector_name} | ${(inspection.started_at ?? inspection.created_at).slice(0, 10)}`,
          columns: OBSERVATION_COLUMNS,
          rows: observations,
        },
      ]);
      download(res, {
        fileName: `inspection-${inspection.ref_no}.xlsx`,
        contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      });
      res.send(buffer);
      return;
    }

    const verification = reportToken(req, {
      reportType: 'inspection',
      entityType: 'inspection',
      entityId: inspection.id,
    });
    streamPdf(
      res,
      {
        fileName: `inspection-${inspection.ref_no}.pdf`,
        title: 'Railway Inspection Report',
        subtitle: `${inspection.module_name} | ${inspection.inspection_type_name}`,
        meta: [
          { label: 'Inspection ID', value: inspection.ref_no },
          { label: 'Location', value: place },
          { label: 'Date', value: (inspection.started_at ?? inspection.created_at).slice(0, 10) },
          { label: 'Location type', value: inspection.location_type },
          { label: 'Inspecting officer', value: `${inspection.inspector_name}${inspection.inspector_designation ? `, ${inspection.inspector_designation}` : ''}` },
          { label: 'Division / Zone', value: [inspection.division_name, inspection.station_category].filter(Boolean).join(' | ') || '-' },
          { label: 'Status', value: inspection.status },
          { label: 'Joint inspection with', value: inspection.joint_with || '-' },
        ],
        verifyUrl: verification.url,
      },
      (doc, helpers) => {
        if (auto?.text) {
          doc.font('Helvetica-Bold').fontSize(9.5).text('Summary');
          doc.moveDown(0.15);
          doc.font('Helvetica').fontSize(8.5).fillColor('#33475b').text(auto.text, { align: 'justify' });
          doc.fillColor('#0b2e4f').moveDown(0.6);
        }
        doc.font('Helvetica-Bold').fontSize(9.5).text(`Observations (${observations.length})`);
        doc.moveDown(0.25);
        if (observations.length === 0) {
          doc.font('Helvetica').fontSize(9).text('No deficiency was noticed during this inspection.');
        } else {
          helpers.table(
            doc,
            [
              { label: 'ID', key: 'ref_no', width: 0.11 },
              { label: 'Unit / Area', key: 'unit_name', width: 0.12 },
              { label: 'Amenity / Item', key: 'item_name', width: 0.13 },
              { label: 'Observation', key: 'observation', width: 0.3 },
              { label: 'Sev.', key: 'severity_name', width: 0.07 },
              { label: 'Action by', key: 'department_name', width: 0.1 },
              { label: 'Supervisor', key: 'supervisor_name', width: 0.1 },
              { label: 'TDC', key: 'tdc', width: 0.07 },
            ],
            observations
          );

          if (req.validQuery.photos) {
            const withPhotos = observations
              .map((o) => ({
                observation: o,
                photos: all(
                  `SELECT * FROM attachments WHERE observation_id = ? AND kind = 'photo' ORDER BY id LIMIT 4`,
                  [o.id]
                ),
              }))
              .filter((x) => x.photos.length);
            if (withPhotos.length) {
              doc.addPage();
              doc.font('Helvetica-Bold').fontSize(11).text('Photographic evidence');
              doc.moveDown(0.4);
              for (const entry of withPhotos) {
                if (doc.y > doc.page.height - 200) doc.addPage();
                doc
                  .font('Helvetica-Bold')
                  .fontSize(8.5)
                  .text(`${entry.observation.ref_no} - ${entry.observation.item_name ?? ''} ${entry.observation.unit_name ? `(${entry.observation.unit_name})` : ''}`);
                doc.font('Helvetica').fontSize(8).fillColor('#5a6b7b').text(entry.observation.observation, { width: 500 });
                doc.fillColor('#0b2e4f').moveDown(0.2);
                let x = 40;
                const top = doc.y;
                let maxBottom = top;
                for (const photo of entry.photos) {
                  const abs = attachmentPath(photo.stored_name);
                  if (!abs) continue;
                  try {
                    doc.image(abs, x, top, { fit: [120, 90] });
                    x += 128;
                    maxBottom = Math.max(maxBottom, top + 90);
                  } catch {
                    /* unreadable image - skip */
                  }
                }
                doc.y = maxBottom + 12;
              }
            }
          }
        }

        if (approvals.length) {
          if (doc.y > doc.page.height - 160) doc.addPage();
          doc.moveDown(0.6);
          doc.font('Helvetica-Bold').fontSize(9.5).text('Acknowledgement & signatures');
          doc.moveDown(0.3);
          for (const a of approvals) {
            const top = doc.y;
            if (a.signature_data?.startsWith('data:image')) {
              try {
                doc.image(Buffer.from(a.signature_data.split(',')[1], 'base64'), 40, top, { fit: [110, 40] });
              } catch {
                /* ignore malformed signature */
              }
            }
            doc
              .font('Helvetica')
              .fontSize(8.5)
              .text(
                `${a.user_name}${a.designation ? `, ${a.designation}` : ''} (${a.approval_role}) - ${String(a.signed_at).slice(0, 19).replace('T', ' ')}${a.remarks ? ` - ${a.remarks}` : ''}`,
                160,
                top + 12,
                { width: doc.page.width - 200 }
              );
            doc.y = Math.max(doc.y, top + 46);
          }
        }
      }
    );
  })
);

/* ----------------------- 2-8. list / analytical reports ------------------- */

router.get('/pending', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Pending Observations Report',
    subtitle: 'Observations awaiting compliance from the concerned department',
    filters: { ...req.validQuery, open: true, sort: 'tdc' },
    reportType: 'pending',
  })
));

router.get('/overdue', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Overdue Observations Report',
    subtitle: 'Observations that have crossed their target date of compliance',
    filters: { ...req.validQuery, overdue: true, sort: 'overdue' },
    reportType: 'overdue',
  })
));

router.get('/critical', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Critical Observations Report',
    subtitle: 'Critical observations and their current status',
    filters: { ...req.validQuery, critical: true },
    reportType: 'critical',
  })
));

router.get('/module-wise', query(filterSchema), asyncRoute(async (req, res) => {
  const modules = all('SELECT * FROM modules WHERE active = 1 ORDER BY sort_order');
  const rows = modules.map((m) => {
    const list = fetchObservations({ ...req.validQuery, module_id: m.id, limit: 5000 }, req.user);
    return {
      module: m.name,
      code: m.code,
      total: list.length,
      pending: list.filter((o) => o.is_open).length,
      overdue: list.filter((o) => o.is_overdue).length,
      closed: list.filter((o) => o.status === 'closed').length,
      critical: list.filter((o) => o.severity_rank === 1).length,
      repeated: list.filter((o) => o.repeat_count > 0).length,
    };
  });
  const columns = [
    { key: 'module', label: 'Module', width: 34 },
    { key: 'total', label: 'Total observations', width: 18 },
    { key: 'pending', label: 'Pending', width: 12 },
    { key: 'overdue', label: 'Overdue', width: 12 },
    { key: 'closed', label: 'Closed', width: 12 },
    { key: 'critical', label: 'Critical', width: 12 },
    { key: 'repeated', label: 'Repeated', width: 12 },
  ];
  await respondWithTable(req, res, {
    title: 'Module-wise Report',
    subtitle: 'Passenger Amenities, Commercial Inspection and Safe Running - Commercial',
    reportType: 'module-wise',
    columns,
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/department-wise', query(filterSchema), asyncRoute(async (req, res) => {
  const { sql, params } = observationFilter(req.validQuery, req.user);
  const rows = all(
    `SELECT o.department_name AS department,
            COUNT(*) AS total,
            SUM(CASE WHEN o.status NOT IN ('closed','cancelled') THEN 1 ELSE 0 END) AS pending,
            SUM(CASE WHEN o.is_open = 1 AND o.days_to_tdc BETWEEN 0 AND 3 THEN 1 ELSE 0 END) AS due_soon,
            SUM(CASE WHEN o.is_overdue = 1 THEN 1 ELSE 0 END) AS overdue,
            SUM(CASE WHEN o.status = 'compliance_submitted' THEN 1 ELSE 0 END) AS compliance_submitted,
            SUM(CASE WHEN o.status = 'closed' THEN 1 ELSE 0 END) AS closed,
            ROUND(AVG(CASE WHEN o.closed_at IS NOT NULL
                 THEN julianday(o.closed_at) - julianday(o.observed_at) END), 1) AS avg_closure_days
       FROM v_observations o WHERE ${sql}
      GROUP BY o.action_by_department_id ORDER BY total DESC`,
    params
  );
  await respondWithTable(req, res, {
    title: 'Department-wise Report',
    subtitle: 'Observations assigned to each department with closure performance',
    reportType: 'department-wise',
    columns: [
      { key: 'department', label: 'Department', width: 22 },
      { key: 'total', label: 'Total assigned', width: 15 },
      { key: 'pending', label: 'Pending', width: 11 },
      { key: 'due_soon', label: 'Due soon', width: 11 },
      { key: 'overdue', label: 'Overdue', width: 11 },
      { key: 'compliance_submitted', label: 'Compliance submitted', width: 20 },
      { key: 'closed', label: 'Closed', width: 10 },
      { key: 'avg_closure_days', label: 'Avg closure (days)', width: 18 },
    ],
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/station-wise', query(filterSchema), asyncRoute(async (req, res) => {
  const { sql, params } = observationFilter(req.validQuery, req.user);
  const rows = all(
    `SELECT o.station_name AS station, o.station_code AS code, o.division_name AS division,
            (SELECT COUNT(*) FROM inspections i WHERE i.station_id = o.station_id) AS inspections,
            COUNT(*) AS observations,
            SUM(CASE WHEN o.status NOT IN ('closed','cancelled') THEN 1 ELSE 0 END) AS pending,
            SUM(CASE WHEN o.is_overdue = 1 THEN 1 ELSE 0 END) AS overdue,
            SUM(CASE WHEN o.status = 'closed' THEN 1 ELSE 0 END) AS closed,
            SUM(CASE WHEN o.repeat_count > 0 THEN 1 ELSE 0 END) AS repeated,
            SUM(CASE WHEN o.module_code = 'PA' THEN 1 ELSE 0 END) AS amenities,
            SUM(CASE WHEN o.module_code = 'CI' THEN 1 ELSE 0 END) AS commercial,
            SUM(CASE WHEN o.module_code = 'SR' THEN 1 ELSE 0 END) AS safe_running
       FROM v_observations o WHERE ${sql} AND o.station_id IS NOT NULL
      GROUP BY o.station_id ORDER BY pending DESC, observations DESC`,
    params
  );
  await respondWithTable(req, res, {
    title: 'Station-wise Report',
    subtitle: 'Inspections, observations, pendency and repeats for each station',
    reportType: 'station-wise',
    columns: [
      { key: 'station', label: 'Station', width: 22 },
      { key: 'code', label: 'Code', width: 8 },
      { key: 'division', label: 'Division', width: 14 },
      { key: 'inspections', label: 'Inspections', width: 12 },
      { key: 'observations', label: 'Observations', width: 13 },
      { key: 'pending', label: 'Pending', width: 10 },
      { key: 'overdue', label: 'Overdue', width: 10 },
      { key: 'closed', label: 'Closed', width: 10 },
      { key: 'repeated', label: 'Repeated', width: 10 },
      { key: 'amenities', label: 'Amenities', width: 11 },
      { key: 'commercial', label: 'Commercial', width: 12 },
      { key: 'safe_running', label: 'Safe running', width: 13 },
    ],
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/repeated-deficiency', query(filterSchema), asyncRoute(async (req, res) => {
  const filters = { ...req.validQuery, days: req.validQuery.days ?? 90 };
  const { sql, params } = observationFilter(filters, req.user);
  const rows = all(
    `SELECT o.station_name AS station, o.station_code AS code, o.unit_name AS unit,
            o.item_name AS item, o.module_name AS module,
            COUNT(*) AS occurrences,
            SUM(CASE WHEN o.status NOT IN ('closed','cancelled') THEN 1 ELSE 0 END) AS still_open,
            MIN(date(o.observed_at)) AS first_seen,
            MAX(date(o.observed_at)) AS last_seen,
            group_concat(o.ref_no) AS observation_ids
       FROM v_observations o
      WHERE ${sql} AND o.item_name IS NOT NULL
      GROUP BY o.station_id, o.unit_name, o.item_name
     HAVING COUNT(*) > 1
      ORDER BY occurrences DESC, last_seen DESC`,
    params
  );
  await respondWithTable(req, res, {
    title: 'Repeated Deficiency Report',
    subtitle: `Recurring deficiencies in the last ${filters.days} days`,
    reportType: 'repeated-deficiency',
    columns: [
      { key: 'station', label: 'Station', width: 20 },
      { key: 'unit', label: 'Unit / Area', width: 18 },
      { key: 'item', label: 'Amenity / Item', width: 22 },
      { key: 'module', label: 'Module', width: 24 },
      { key: 'occurrences', label: 'Times observed', width: 15 },
      { key: 'still_open', label: 'Still open', width: 11 },
      { key: 'first_seen', label: 'First seen', width: 12 },
      { key: 'last_seen', label: 'Last seen', width: 12 },
      { key: 'observation_ids', label: 'Observation IDs', width: 40 },
    ],
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/compliance', query(filterSchema), asyncRoute(async (req, res) => {
  const f = req.validQuery;
  const where = ['1=1'];
  const params = [];
  if (f.from) {
    where.push('date(c.submitted_at) >= date(?)');
    params.push(f.from);
  }
  if (f.to) {
    where.push('date(c.submitted_at) <= date(?)');
    params.push(f.to);
  }
  if (f.station_id) {
    where.push('o.station_id = ?');
    params.push(f.station_id);
  }
  if (f.department_id) {
    where.push('o.action_by_department_id = ?');
    params.push(f.department_id);
  }
  if (f.module_id) {
    where.push('o.module_id = ?');
    params.push(f.module_id);
  }
  const rows = all(
    `SELECT o.ref_no AS observation_id, o.station_name AS station, o.unit_name AS unit,
            o.item_name AS item, o.observation, o.severity_name AS severity,
            o.department_name AS action_by, o.tdc, c.round,
            c.action_taken, c.remarks, date(c.compliance_date) AS compliance_date,
            c.status AS compliance_status, u.name AS submitted_by,
            v.name AS verified_by, date(c.verified_at) AS verified_on,
            c.rejection_reason, o.status AS observation_status,
            date(o.closed_at) AS closed_on,
            (SELECT COUNT(*) FROM attachments a WHERE a.compliance_id = c.id) AS evidence_files
       FROM compliances c
       JOIN v_observations o ON o.id = c.observation_id
       JOIN users u ON u.id = c.submitted_by
       LEFT JOIN users v ON v.id = c.verified_by
      WHERE ${where.join(' AND ')}
      ORDER BY c.submitted_at DESC LIMIT ?`,
    [...params, f.limit]
  );
  await respondWithTable(req, res, {
    title: 'Compliance Report',
    subtitle: 'Action taken, compliance date, verification and closure',
    reportType: 'compliance',
    columns: [
      { key: 'observation_id', label: 'Observation ID', width: 16 },
      { key: 'station', label: 'Station', width: 18 },
      { key: 'unit', label: 'Unit', width: 16 },
      { key: 'item', label: 'Item', width: 20 },
      { key: 'observation', label: 'Observation', width: 44 },
      { key: 'action_by', label: 'Action by', width: 14 },
      { key: 'tdc', label: 'TDC', width: 11 },
      { key: 'round', label: 'Round', width: 8 },
      { key: 'action_taken', label: 'Action taken', width: 44 },
      { key: 'compliance_date', label: 'Compliance date', width: 15 },
      { key: 'submitted_by', label: 'Submitted by', width: 20 },
      { key: 'compliance_status', label: 'Verification', width: 16 },
      { key: 'verified_by', label: 'Verified by', width: 20 },
      { key: 'verified_on', label: 'Verified on', width: 12 },
      { key: 'rejection_reason', label: 'Rejection reason', width: 30 },
      { key: 'observation_status', label: 'Observation status', width: 18 },
      { key: 'closed_on', label: 'Closed on', width: 12 },
    ],
    rows,
    format: f.format,
  });
}));

/** Shared renderer for the aggregate reports. */
async function respondWithTable(req, res, { title, subtitle, reportType, columns, rows, format = 'json' }) {
  const fileBase = `${reportType}-${stamp()}`;
  if (format === 'json') {
    res.json({ title, subtitle, generated_at: nowIso(), count: rows.length, data: rows });
    return;
  }
  if (format === 'csv') {
    download(res, { fileName: `${fileBase}.csv`, contentType: 'text/csv; charset=utf-8' });
    res.send(toCsv(rows, columns));
    return;
  }
  if (format === 'xlsx') {
    const buffer = await toXlsx([{ name: reportType.slice(0, 28), title, subtitle, columns, rows }]);
    download(res, {
      fileName: `${fileBase}.xlsx`,
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    res.send(buffer);
    return;
  }
  const verification = reportToken(req, { reportType, params: req.validQuery });
  const widthSum = columns.length;
  streamPdf(
    res,
    {
      fileName: `${fileBase}.pdf`,
      title,
      subtitle,
      meta: [
        { label: 'Rows', value: rows.length },
        { label: 'Generated by', value: `${req.user.name}${req.user.designation ? `, ${req.user.designation}` : ''}` },
      ],
      verifyUrl: verification.url,
    },
    (doc, helpers) => {
      helpers.table(
        doc,
        columns.map((c) => ({ ...c, width: 1 / widthSum })),
        rows,
        { fontSize: columns.length > 10 ? 6.5 : 8 }
      );
    }
  );
}

/* --------------------------- raw observation export ---------------------- */

router.get('/observations', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Observation Register',
    subtitle: 'Filtered observation export',
    filters: req.validQuery,
    reportType: 'observations',
  })
));

/* ----------------------------- audit trail export ------------------------ */

router.get(
  '/audit',
  query(
    z.object({
      format: z.enum(['json', 'csv', 'xlsx']).default('json'),
      entity_type: optionalText,
      entity_id: optionalText,
      user_id: optionalId,
      action: optionalText,
      from: optionalIsoDate,
      to: optionalIsoDate,
      limit: z.coerce.number().int().min(1).max(5000).default(500),
    })
  ),
  asyncRoute(async (req, res) => {
    if (!['admin', 'divisional_officer'].includes(req.user.role)) {
      throw badRequest('Only an administrator or divisional officer can export the audit trail');
    }
    const f = req.validQuery;
    const where = ['1=1'];
    const params = [];
    for (const [col, val] of [
      ['entity_type', f.entity_type],
      ['entity_id', f.entity_id],
      ['user_id', f.user_id],
      ['action', f.action],
    ]) {
      if (val !== undefined) {
        where.push(`${col} = ?`);
        params.push(val);
      }
    }
    if (f.from) {
      where.push('date(created_at) >= date(?)');
      params.push(f.from);
    }
    if (f.to) {
      where.push('date(created_at) <= date(?)');
      params.push(f.to);
    }
    const rows = all(
      `SELECT id, created_at, user_name, role, action, entity_type, entity_id, remarks,
              previous_value, new_value, ip
         FROM audit_log WHERE ${where.join(' AND ')} ORDER BY id DESC LIMIT ?`,
      [...params, f.limit]
    );
    const columns = [
      { key: 'created_at', label: 'Timestamp', width: 22 },
      { key: 'user_name', label: 'User', width: 22 },
      { key: 'role', label: 'Role', width: 16 },
      { key: 'action', label: 'Action', width: 24 },
      { key: 'entity_type', label: 'Entity', width: 14 },
      { key: 'entity_id', label: 'Entity ID', width: 12 },
      { key: 'remarks', label: 'Remarks', width: 40 },
      { key: 'previous_value', label: 'Previous value', width: 50 },
      { key: 'new_value', label: 'New value', width: 50 },
      { key: 'ip', label: 'IP', width: 14 },
    ];
    await respondWithTable(req, res, {
      title: 'Audit Trail',
      subtitle: 'User, date, time, action, previous value and new value',
      reportType: 'audit',
      columns,
      rows,
      format: f.format,
    });
  })
);

export default router;
