import express from 'express';
import config from '../config.js';
import { all, get, insert, nowIso } from '../db/index.js';
import { randomToken } from '../lib/ids.js';
import { notFound, badRequest } from '../lib/errors.js';
import { authenticate, requireCapability } from '../middleware/auth.js';
import { asyncRoute, download } from '../lib/http.js';
import { query, z, optionalId, optionalText, optionalIsoDate, optionalBool } from '../lib/validate.js';
import { observationFilter, decorate } from '../lib/queries.js';
import { toCsv, toXlsx, streamPdf, streamInspectionReportPdf, attachmentPath } from '../lib/exporters.js';
import { reportFor } from '../lib/inspectionReport.js';
import { inspectionScopeClause } from '../lib/queries.js';

const router = express.Router();

/* -------------------------------------------------------------------------- */
/* Public QR verification - deliberately mounted before the auth guard        */
/* -------------------------------------------------------------------------- */

/**
 * Anyone holding a printed report can scan its QR code and confirm that the
 * document was generated by this system, and that its figures still match.
 */
router.get('/verify/:token', (req, res) => {
  const token = get('SELECT * FROM report_tokens WHERE token = ?', [req.params.token]);
  if (!token) throw notFound('Report');
  const user = token.generated_by ? get('SELECT name, designation FROM users WHERE id = ?', [token.generated_by]) : null;
  const response = {
    verified: true,
    report_type: token.report_type,
    generated_at: token.generated_at,
    generated_by: user ? { name: user.name, designation: user.designation } : null,
  };
  if (token.entity_type === 'inspection') {
    const inspection = get('SELECT * FROM v_inspections i WHERE i.id = ?', [token.entity_id]);
    if (inspection) {
      response.inspection = {
        ref_no: inspection.ref_no,
        type: inspection.inspection_type_name,
        module: inspection.module_name,
        station: inspection.station_name,
        train: inspection.train_number,
        inspector: inspection.inspector_name,
        date: (inspection.started_at ?? inspection.created_at).slice(0, 10),
        status: inspection.status,
        observations: inspection.observation_count,
        open_observations: inspection.open_count,
        closed_observations: inspection.closed_count,
      };
    }
  }
  res.json(response);
});

router.use(authenticate);
router.use(requireCapability('report:read'));

const FORMATS = ['json', 'csv', 'xlsx', 'pdf'];

const filterSchema = z.object({
  format: z.enum(FORMATS).default('json'),
  module_id: optionalId,
  module_code: optionalText,
  station_id: optionalId,
  division_id: optionalId,
  department_id: optionalId,
  supervisor_id: optionalId,
  severity_id: optionalId,
  status: optionalText,
  from: optionalIsoDate,
  to: optionalIsoDate,
  days: z.coerce.number().int().min(1).max(3650).optional(),
  q: optionalText,
  mine: optionalBool,
  limit: z.coerce.number().int().min(1).max(5000).default(1000),
});

const OBSERVATION_COLUMNS = [
  { key: 'ref_no', label: 'Observation ID', width: 18 },
  { key: 'module_name', label: 'Module', width: 26 },
  { key: 'inspection_ref', label: 'Inspection', width: 18 },
  { key: 'observed_at', label: 'Date', width: 12, value: (r) => String(r.observed_at).slice(0, 10) },
  { key: 'station_name', label: 'Station', width: 20 },
  { key: 'station_code', label: 'Code', width: 8 },
  { key: 'train_number', label: 'Train', width: 12 },
  { key: 'unit_name', label: 'Unit / Area', width: 20 },
  { key: 'item_name', label: 'Amenity / Item', width: 24 },
  { key: 'category_name', label: 'Category', width: 18 },
  { key: 'observation', label: 'Observation', width: 60 },
  { key: 'severity_name', label: 'Severity', width: 12 },
  { key: 'department_name', label: 'Action by', width: 16 },
  { key: 'supervisor_name', label: 'Concerned supervisor', width: 24 },
  { key: 'supervisor_mobile', label: 'Mobile', width: 14 },
  { key: 'tdc', label: 'TDC', width: 12 },
  { key: 'status', label: 'Status', width: 20, value: (r) => statusLabel(r.status) },
  { key: 'is_overdue', label: 'Overdue', width: 9, value: (r) => (r.is_overdue ? 'Yes' : 'No') },
  { key: 'repeat_count', label: 'Repeated', width: 10 },
  { key: 'inspector_name', label: 'Inspecting officer', width: 22 },
  { key: 'closed_at', label: 'Closed on', width: 12, value: (r) => (r.closed_at ? String(r.closed_at).slice(0, 10) : '') },
];

const STATUS_LABELS = {
  submitted: 'Submitted',
  assigned: 'Assigned',
  acknowledged: 'Acknowledged',
  in_progress: 'Action in progress',
  compliance_submitted: 'Compliance submitted',
  verified: 'Verified',
  closed: 'Closed',
  rejected: 'Rejected',
  reopened: 'Reopened',
  cancelled: 'Cancelled',
};
const statusLabel = (s) => STATUS_LABELS[s] ?? s;

function fetchObservations(filters, user) {
  const { sql, params } = observationFilter(filters, user);
  return all(
    `SELECT * FROM v_observations o WHERE ${sql}
      ORDER BY o.is_overdue DESC, o.severity_rank ASC, o.observed_at DESC LIMIT ?`,
    [...params, filters.limit ?? 1000]
  ).map(decorate);
}

function reportToken(req, { reportType, entityType = null, entityId = null, params = null }) {
  const token = randomToken(12);
  insert('report_tokens', {
    token,
    report_type: reportType,
    entity_type: entityType,
    entity_id: entityId,
    params: params ? JSON.stringify(params) : null,
    generated_by: req.user.id,
  });
  return { token, url: `${config.publicUrl}/api/reports/verify/${token}` };
}

const stamp = () => new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-');

/** Renders one observation list as JSON, CSV, Excel or PDF. */
async function respondWithObservations(req, res, { title, subtitle, filters, meta = [], reportType }) {
  const rows = fetchObservations(filters, req.user);
  const format = filters.format ?? 'json';
  const fileBase = `${reportType}-${stamp()}`;

  if (format === 'json') {
    res.json({ title, subtitle, generated_at: nowIso(), count: rows.length, data: rows });
    return;
  }
  if (format === 'csv') {
    download(res, { fileName: `${fileBase}.csv`, contentType: 'text/csv; charset=utf-8' });
    res.send(toCsv(rows, OBSERVATION_COLUMNS));
    return;
  }
  if (format === 'xlsx') {
    const buffer = await toXlsx([
      { name: 'Observations', title, subtitle, columns: OBSERVATION_COLUMNS, rows },
      {
        name: 'Summary',
        title: 'Summary',
        columns: [
          { key: 'metric', label: 'Metric', width: 30 },
          { key: 'value', label: 'Value', width: 14 },
        ],
        rows: summaryRows(rows),
      },
    ]);
    download(res, {
      fileName: `${fileBase}.xlsx`,
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    res.send(buffer);
    return;
  }

  const verification = reportToken(req, { reportType, params: filters });
  streamPdf(
    res,
    {
      fileName: `${fileBase}.pdf`,
      title,
      subtitle,
      meta: [
        ...meta,
        { label: 'Observations', value: rows.length },
        { label: 'Generated by', value: `${req.user.name}${req.user.designation ? `, ${req.user.designation}` : ''}` },
      ],
      verifyUrl: verification.url,
    },
    (doc, helpers) => {
      helpers.table(
        doc,
        [
          { label: 'ID', key: 'ref_no', width: 0.1 },
          { label: 'Station / Train', width: 0.13, value: (r) => r.location_label },
          { label: 'Unit', key: 'unit_name', width: 0.1 },
          { label: 'Item', key: 'item_name', width: 0.11 },
          { label: 'Observation', key: 'observation', width: 0.26 },
          { label: 'Sev.', key: 'severity_name', width: 0.06 },
          { label: 'Action by', key: 'department_name', width: 0.09 },
          { label: 'TDC', key: 'tdc', width: 0.07 },
          { label: 'Status', width: 0.08, value: (r) => statusLabel(r.status) },
        ],
        rows
      );
      doc.moveDown(0.3);
      doc.font('Helvetica-Bold').fontSize(9).text('Summary');
      doc.font('Helvetica').fontSize(8.5);
      for (const row of summaryRows(rows)) doc.text(`${row.metric}: ${row.value}`);
    }
  );
}

function summaryRows(rows) {
  const open = rows.filter((r) => r.is_open).length;
  const overdue = rows.filter((r) => r.is_overdue).length;
  const closed = rows.filter((r) => r.status === 'closed').length;
  const critical = rows.filter((r) => r.severity_rank === 1).length;
  const repeated = rows.filter((r) => r.repeat_count > 0).length;
  const byDept = {};
  for (const r of rows) byDept[r.department_name] = (byDept[r.department_name] ?? 0) + 1;
  return [
    { metric: 'Total observations', value: rows.length },
    { metric: 'Open', value: open },
    { metric: 'Overdue', value: overdue },
    { metric: 'Closed', value: closed },
    { metric: 'Critical', value: critical },
    { metric: 'Repeated deficiencies', value: repeated },
    ...Object.entries(byDept)
      .sort((a, b) => b[1] - a[1])
      .map(([k, v]) => ({ metric: `Action by ${k}`, value: v })),
  ];
}

/* ------------------------------ report catalogue -------------------------- */

router.get('/catalogue', (_req, res) => {
  res.json({
    formats: FORMATS,
    data: [
      { key: 'inspection', name: 'Inspection Report', path: '/api/reports/inspection/:id', description: 'One inspection in full: areas covered, items checked, deficiencies, previous-inspection review and signatures', entity: 'inspection' },
      { key: 'inspection-register', name: 'Inspection Register', path: '/api/reports/inspection-register', description: 'One row per inspection - what inspection work was done, how much of each station was covered' },
      { key: 'inspector-wise', name: 'Inspector-wise Report', path: '/api/reports/inspector-wise', description: 'Inspections, coverage and closure by the officer who carried them out' },
      { key: 'compliance', name: 'Compliance Report', path: '/api/reports/compliance', description: 'Action taken, compliance date, verification and closure' },
      { key: 'pending', name: 'Pending Report', path: '/api/reports/pending', description: 'Every observation awaiting compliance' },
      { key: 'overdue', name: 'Overdue Report', path: '/api/reports/overdue', description: 'Observations past their target date of compliance' },
      { key: 'department-wise', name: 'Department-wise Report', path: '/api/reports/department-wise', description: 'Workload and closure performance by department' },
      { key: 'station-wise', name: 'Station-wise Report', path: '/api/reports/station-wise', description: 'Observations, pendency and repeats by station' },
      { key: 'repeated-deficiency', name: 'Repeated Deficiency Report', path: '/api/reports/repeated-deficiency', description: 'Recurring deficiencies with occurrence counts' },
      { key: 'module-wise', name: 'Module-wise Report', path: '/api/reports/module-wise', description: 'Passenger Amenities, Commercial and Safe Running side by side' },
    ],
  });
});

/* ------------------------- 1. the inspection report ----------------------- */

/** Flattened area rows, for the CSV and Excel forms of the report. */
const AREA_COLUMNS = [
  { label: 'Sl', key: 'sl' },
  { label: 'Area', key: 'unit_name' },
  { label: 'Result', key: 'result_label' },
  { label: 'Items checked', key: 'items_count' },
  { label: 'Found in order', key: 'ok_count' },
  { label: 'Deficiencies', key: 'deficiency_count' },
  { label: 'Remarks', key: 'remarks' },
  { label: 'Inspected at', key: 'inspected_at' },
];

const ITEM_RESULT_COLUMNS = [
  { label: 'Area', key: 'area_name' },
  { label: 'Group', key: 'group_name' },
  { label: 'Item', key: 'item_name' },
  { label: 'Result', key: 'result' },
  { label: 'Remarks', key: 'remarks' },
  { label: 'Observation', key: 'observation_ref' },
];

const PREVIOUS_COLUMNS = [
  { label: 'Sl', key: 'sl' },
  { label: 'Ref', key: 'ref_no' },
  { label: 'Area', key: 'unit_name' },
  { label: 'Item', key: 'item_name' },
  { label: 'Deficiency', key: 'observation' },
  { label: 'Action by', key: 'department_name' },
  { label: 'TDC', key: 'tdc' },
  { label: 'Position at this inspection', key: 'finding_label' },
  { label: 'Remarks', key: 'review_remarks' },
];

/** The area rows the flat formats print. */
function areaRows(report) {
  return report.areas.map((area, i) => ({
    sl: i + 1,
    unit_name: area.unit_name,
    result: area.result,
    result_label: area.result_label,
    items_count: area.items.length,
    ok_count: area.items_ok.length,
    deficiency_count: area.observations.length,
    remarks: area.remarks ?? '',
    inspected_at: area.inspected_at ?? '',
  }));
}

function itemResultRows(report) {
  const byId = new Map(report.observations.map((o) => [o.id, o.ref_no]));
  return report.areas.flatMap((area) =>
    area.items.map((r) => ({
      area_name: area.unit_name,
      group_name: r.group_name ?? '',
      item_name: r.item_name,
      result: r.result,
      remarks: r.remarks ?? '',
      observation_ref: r.observation_id ? byId.get(r.observation_id) ?? '' : '',
    }))
  );
}

function previousRows(report) {
  return report.previous_items.map((item, i) => ({
    sl: i + 1,
    ref_no: item.ref_no,
    unit_name: item.unit_name ?? '',
    item_name: item.item_name ?? '',
    observation: item.observation,
    department_name: item.department_name,
    tdc: item.tdc ?? '',
    finding_label: item.finding_label,
    review_remarks: item.review?.remarks ?? '',
  }));
}

/**
 * The inspection report: one visit by one officer over as many areas as were
 * attended to. PDF is the office form; CSV and Excel carry the same parts as
 * sheets so they can be worked on.
 */
router.get(
  '/inspection/:id',
  query(z.object({ format: z.enum(FORMATS).default('json'), photos: optionalBool.default(true) })),
  asyncRoute(async (req, res) => {
    const report = reportFor(Number(req.params.id));
    const { inspection } = report;
    const { format } = req.validQuery;
    const stem = `inspection-${(inspection.inspection_no ?? inspection.ref_no).replace(/[^A-Za-z0-9-]+/g, '-')}`;

    if (format === 'json') {
      res.json(report);
      return;
    }
    if (format === 'csv') {
      // One file, the parts stacked - the shape a clerk can paste into a return.
      // One file with the parts stacked. The byte-order mark goes at the very top
      // and nowhere else, so the inner tables are asked for without one.
      const parts = [
        `﻿Inspection Report,${inspection.inspection_no ?? inspection.ref_no}`,
        `Location,${report.place.name}`,
        `Date,${(inspection.started_at ?? inspection.created_at ?? '').slice(0, 10)}`,
        `Inspecting officer,"${inspection.inspector_name}"`,
        `Areas on sheet,${report.coverage.areas_on_sheet}`,
        `Areas attended to,${report.coverage.areas_covered}`,
        `Items checked,${report.coverage.items_checked}`,
        '',
        'PART I - Review of the previous inspection',
        toCsv(previousRows(report), PREVIOUS_COLUMNS, { bom: false }),
        '',
        'PART II - Areas inspected',
        toCsv(areaRows(report), AREA_COLUMNS, { bom: false }),
        '',
        'PART III - Deficiencies noticed',
        toCsv(report.observations.map(decorate), OBSERVATION_COLUMNS, { bom: false }),
        '',
        'PART IV - Items checked, with result',
        toCsv(itemResultRows(report), ITEM_RESULT_COLUMNS, { bom: false }),
      ];
      download(res, { fileName: `${stem}.csv`, contentType: 'text/csv; charset=utf-8' });
      res.send(parts.join('\n'));
      return;
    }
    if (format === 'xlsx') {
      const subtitle = `${inspection.ref_no} | ${inspection.inspector_name} | ${(inspection.started_at ?? inspection.created_at ?? '').slice(0, 10)}`;
      const buffer = await toXlsx([
        {
          name: 'Areas',
          title: `Areas inspected - ${report.place.name}`,
          subtitle,
          columns: AREA_COLUMNS,
          rows: areaRows(report),
        },
        {
          name: 'Deficiencies',
          title: `Deficiencies noticed - ${report.place.name}`,
          subtitle,
          columns: OBSERVATION_COLUMNS,
          rows: report.observations.map(decorate),
        },
        {
          name: 'Items',
          title: 'Items checked, with result',
          subtitle,
          columns: ITEM_RESULT_COLUMNS,
          rows: itemResultRows(report),
        },
        {
          name: 'Previous inspection',
          title: 'Review of the previous inspection',
          subtitle,
          columns: PREVIOUS_COLUMNS,
          rows: previousRows(report),
        },
      ]);
      download(res, {
        fileName: `${stem}.xlsx`,
        contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      });
      res.send(buffer);
      return;
    }

    const verification = reportToken(req, {
      reportType: 'inspection',
      entityType: 'inspection',
      entityId: inspection.id,
    });
    const photos = req.validQuery.photos
      ? report.observations
          .map((o) => ({
            observation: o,
            photos: all(
              `SELECT * FROM attachments WHERE observation_id = ? AND kind = 'photo' ORDER BY id LIMIT 4`,
              [o.id]
            ),
          }))
          .filter((x) => x.photos.length)
      : [];
    streamInspectionReportPdf(res, report, {
      fileName: `${stem}.pdf`,
      verifyUrl: verification.url,
      photos,
      attachmentPath,
    });
  })
);

/* ----------------------- 2-8. list / analytical reports ------------------- */

router.get('/pending', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Pending Observations Report',
    subtitle: 'Observations awaiting compliance from the concerned department',
    filters: { ...req.validQuery, open: true, sort: 'tdc' },
    reportType: 'pending',
  })
));

router.get('/overdue', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Overdue Observations Report',
    subtitle: 'Observations that have crossed their target date of compliance',
    filters: { ...req.validQuery, overdue: true, sort: 'overdue' },
    reportType: 'overdue',
  })
));

router.get('/critical', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Critical Observations Report',
    subtitle: 'Critical observations and their current status',
    filters: { ...req.validQuery, critical: true },
    reportType: 'critical',
  })
));

router.get('/module-wise', query(filterSchema), asyncRoute(async (req, res) => {
  const modules = all('SELECT * FROM modules WHERE active = 1 ORDER BY sort_order');
  const rows = modules.map((m) => {
    const list = fetchObservations({ ...req.validQuery, module_id: m.id, limit: 5000 }, req.user);
    return {
      module: m.name,
      code: m.code,
      total: list.length,
      pending: list.filter((o) => o.is_open).length,
      overdue: list.filter((o) => o.is_overdue).length,
      closed: list.filter((o) => o.status === 'closed').length,
      critical: list.filter((o) => o.severity_rank === 1).length,
      repeated: list.filter((o) => o.repeat_count > 0).length,
    };
  });
  const columns = [
    { key: 'module', label: 'Module', width: 34 },
    { key: 'total', label: 'Total observations', width: 18 },
    { key: 'pending', label: 'Pending', width: 12 },
    { key: 'overdue', label: 'Overdue', width: 12 },
    { key: 'closed', label: 'Closed', width: 12 },
    { key: 'critical', label: 'Critical', width: 12 },
    { key: 'repeated', label: 'Repeated', width: 12 },
  ];
  await respondWithTable(req, res, {
    title: 'Module-wise Report',
    subtitle: 'Passenger Amenities, Commercial Inspection and Safe Running - Commercial',
    reportType: 'module-wise',
    columns,
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/department-wise', query(filterSchema), asyncRoute(async (req, res) => {
  const { sql, params } = observationFilter(req.validQuery, req.user);
  const rows = all(
    `SELECT o.department_name AS department,
            COUNT(*) AS total,
            SUM(CASE WHEN o.status NOT IN ('closed','cancelled') THEN 1 ELSE 0 END) AS pending,
            SUM(CASE WHEN o.is_open = 1 AND o.days_to_tdc BETWEEN 0 AND 3 THEN 1 ELSE 0 END) AS due_soon,
            SUM(CASE WHEN o.is_overdue = 1 THEN 1 ELSE 0 END) AS overdue,
            SUM(CASE WHEN o.status = 'compliance_submitted' THEN 1 ELSE 0 END) AS compliance_submitted,
            SUM(CASE WHEN o.status = 'closed' THEN 1 ELSE 0 END) AS closed,
            ROUND(AVG(CASE WHEN o.closed_at IS NOT NULL
                 THEN julianday(o.closed_at) - julianday(o.observed_at) END), 1) AS avg_closure_days
       FROM v_observations o WHERE ${sql}
      GROUP BY o.action_by_department_id ORDER BY total DESC`,
    params
  );
  await respondWithTable(req, res, {
    title: 'Department-wise Report',
    subtitle: 'Observations assigned to each department with closure performance',
    reportType: 'department-wise',
    columns: [
      { key: 'department', label: 'Department', width: 22 },
      { key: 'total', label: 'Total assigned', width: 15 },
      { key: 'pending', label: 'Pending', width: 11 },
      { key: 'due_soon', label: 'Due soon', width: 11 },
      { key: 'overdue', label: 'Overdue', width: 11 },
      { key: 'compliance_submitted', label: 'Compliance submitted', width: 20 },
      { key: 'closed', label: 'Closed', width: 10 },
      { key: 'avg_closure_days', label: 'Avg closure (days)', width: 18 },
    ],
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/station-wise', query(filterSchema), asyncRoute(async (req, res) => {
  const { sql, params } = observationFilter(req.validQuery, req.user);
  const rows = all(
    `SELECT o.station_name AS station, o.station_code AS code, o.division_name AS division,
            (SELECT COUNT(*) FROM inspections i WHERE i.station_id = o.station_id) AS inspections,
            COUNT(*) AS observations,
            SUM(CASE WHEN o.status NOT IN ('closed','cancelled') THEN 1 ELSE 0 END) AS pending,
            SUM(CASE WHEN o.is_overdue = 1 THEN 1 ELSE 0 END) AS overdue,
            SUM(CASE WHEN o.status = 'closed' THEN 1 ELSE 0 END) AS closed,
            SUM(CASE WHEN o.repeat_count > 0 THEN 1 ELSE 0 END) AS repeated,
            SUM(CASE WHEN o.module_code = 'PA' THEN 1 ELSE 0 END) AS amenities,
            SUM(CASE WHEN o.module_code = 'CI' THEN 1 ELSE 0 END) AS commercial,
            SUM(CASE WHEN o.module_code = 'SR' THEN 1 ELSE 0 END) AS safe_running
       FROM v_observations o WHERE ${sql} AND o.station_id IS NOT NULL
      GROUP BY o.station_id ORDER BY pending DESC, observations DESC`,
    params
  );
  await respondWithTable(req, res, {
    title: 'Station-wise Report',
    subtitle: 'Inspections, observations, pendency and repeats for each station',
    reportType: 'station-wise',
    columns: [
      { key: 'station', label: 'Station', width: 22 },
      { key: 'code', label: 'Code', width: 8 },
      { key: 'division', label: 'Division', width: 14 },
      { key: 'inspections', label: 'Inspections', width: 12 },
      { key: 'observations', label: 'Observations', width: 13 },
      { key: 'pending', label: 'Pending', width: 10 },
      { key: 'overdue', label: 'Overdue', width: 10 },
      { key: 'closed', label: 'Closed', width: 10 },
      { key: 'repeated', label: 'Repeated', width: 10 },
      { key: 'amenities', label: 'Amenities', width: 11 },
      { key: 'commercial', label: 'Commercial', width: 12 },
      { key: 'safe_running', label: 'Safe running', width: 13 },
    ],
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/repeated-deficiency', query(filterSchema), asyncRoute(async (req, res) => {
  const filters = { ...req.validQuery, days: req.validQuery.days ?? 90 };
  const { sql, params } = observationFilter(filters, req.user);
  const rows = all(
    `SELECT o.station_name AS station, o.station_code AS code, o.unit_name AS unit,
            o.item_name AS item, o.module_name AS module,
            COUNT(*) AS occurrences,
            SUM(CASE WHEN o.status NOT IN ('closed','cancelled') THEN 1 ELSE 0 END) AS still_open,
            MIN(date(o.observed_at)) AS first_seen,
            MAX(date(o.observed_at)) AS last_seen,
            group_concat(o.ref_no) AS observation_ids
       FROM v_observations o
      WHERE ${sql} AND o.item_name IS NOT NULL
      GROUP BY o.station_id, o.unit_name, o.item_name
     HAVING COUNT(*) > 1
      ORDER BY occurrences DESC, last_seen DESC`,
    params
  );
  await respondWithTable(req, res, {
    title: 'Repeated Deficiency Report',
    subtitle: `Recurring deficiencies in the last ${filters.days} days`,
    reportType: 'repeated-deficiency',
    columns: [
      { key: 'station', label: 'Station', width: 20 },
      { key: 'unit', label: 'Unit / Area', width: 18 },
      { key: 'item', label: 'Amenity / Item', width: 22 },
      { key: 'module', label: 'Module', width: 24 },
      { key: 'occurrences', label: 'Times observed', width: 15 },
      { key: 'still_open', label: 'Still open', width: 11 },
      { key: 'first_seen', label: 'First seen', width: 12 },
      { key: 'last_seen', label: 'Last seen', width: 12 },
      { key: 'observation_ids', label: 'Observation IDs', width: 40 },
    ],
    rows,
    format: req.validQuery.format,
  });
}));

router.get('/compliance', query(filterSchema), asyncRoute(async (req, res) => {
  const f = req.validQuery;
  const where = ['1=1'];
  const params = [];
  if (f.from) {
    where.push('date(c.submitted_at) >= date(?)');
    params.push(f.from);
  }
  if (f.to) {
    where.push('date(c.submitted_at) <= date(?)');
    params.push(f.to);
  }
  if (f.station_id) {
    where.push('o.station_id = ?');
    params.push(f.station_id);
  }
  if (f.department_id) {
    where.push('o.action_by_department_id = ?');
    params.push(f.department_id);
  }
  if (f.module_id) {
    where.push('o.module_id = ?');
    params.push(f.module_id);
  }
  const rows = all(
    `SELECT o.ref_no AS observation_id, o.station_name AS station, o.unit_name AS unit,
            o.item_name AS item, o.observation, o.severity_name AS severity,
            o.department_name AS action_by, o.tdc, c.round,
            c.action_taken, c.remarks, date(c.compliance_date) AS compliance_date,
            c.status AS compliance_status, u.name AS submitted_by,
            v.name AS verified_by, date(c.verified_at) AS verified_on,
            c.rejection_reason, o.status AS observation_status,
            date(o.closed_at) AS closed_on,
            (SELECT COUNT(*) FROM attachments a WHERE a.compliance_id = c.id) AS evidence_files
       FROM compliances c
       JOIN v_observations o ON o.id = c.observation_id
       JOIN users u ON u.id = c.submitted_by
       LEFT JOIN users v ON v.id = c.verified_by
      WHERE ${where.join(' AND ')}
      ORDER BY c.submitted_at DESC LIMIT ?`,
    [...params, f.limit]
  );
  await respondWithTable(req, res, {
    title: 'Compliance Report',
    subtitle: 'Action taken, compliance date, verification and closure',
    reportType: 'compliance',
    columns: [
      { key: 'observation_id', label: 'Observation ID', width: 16 },
      { key: 'station', label: 'Station', width: 18 },
      { key: 'unit', label: 'Unit', width: 16 },
      { key: 'item', label: 'Item', width: 20 },
      { key: 'observation', label: 'Observation', width: 44 },
      { key: 'action_by', label: 'Action by', width: 14 },
      { key: 'tdc', label: 'TDC', width: 11 },
      { key: 'round', label: 'Round', width: 8 },
      { key: 'action_taken', label: 'Action taken', width: 44 },
      { key: 'compliance_date', label: 'Compliance date', width: 15 },
      { key: 'submitted_by', label: 'Submitted by', width: 20 },
      { key: 'compliance_status', label: 'Verification', width: 16 },
      { key: 'verified_by', label: 'Verified by', width: 20 },
      { key: 'verified_on', label: 'Verified on', width: 12 },
      { key: 'rejection_reason', label: 'Rejection reason', width: 30 },
      { key: 'observation_status', label: 'Observation status', width: 18 },
      { key: 'closed_on', label: 'Closed on', width: 12 },
    ],
    rows,
    format: f.format,
  });
}));

/** Shared renderer for the aggregate reports. */
async function respondWithTable(req, res, { title, subtitle, reportType, columns, rows, format = 'json' }) {
  const fileBase = `${reportType}-${stamp()}`;
  if (format === 'json') {
    res.json({ title, subtitle, generated_at: nowIso(), count: rows.length, data: rows });
    return;
  }
  if (format === 'csv') {
    download(res, { fileName: `${fileBase}.csv`, contentType: 'text/csv; charset=utf-8' });
    res.send(toCsv(rows, columns));
    return;
  }
  if (format === 'xlsx') {
    const buffer = await toXlsx([{ name: reportType.slice(0, 28), title, subtitle, columns, rows }]);
    download(res, {
      fileName: `${fileBase}.xlsx`,
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    res.send(buffer);
    return;
  }
  const verification = reportToken(req, { reportType, params: req.validQuery });
  const widthSum = columns.length;
  streamPdf(
    res,
    {
      fileName: `${fileBase}.pdf`,
      title,
      subtitle,
      meta: [
        { label: 'Rows', value: rows.length },
        { label: 'Generated by', value: `${req.user.name}${req.user.designation ? `, ${req.user.designation}` : ''}` },
      ],
      verifyUrl: verification.url,
    },
    (doc, helpers) => {
      helpers.table(
        doc,
        columns.map((c) => ({ ...c, width: 1 / widthSum })),
        rows,
        { fontSize: columns.length > 10 ? 6.5 : 8 }
      );
    }
  );
}

/* ------------------- 9-10. the inspection-based reports ------------------- */

/**
 * These two are the reports that read the inspection as the unit of record.
 *
 * Everything above counts observations, which answers "what is wrong and who has
 * to fix it". These answer the other half: what inspection work was done. One
 * commercial inspector covers many areas in a visit, so the register has one row
 * per visit - not per area - and the inspector-wise report sums those visits.
 */

const INSPECTION_COLUMNS = [
  { key: 'inspection_no', label: 'Report No.', width: 24 },
  { key: 'ref_no', label: 'Inspection ID', width: 18 },
  { key: 'date', label: 'Date', width: 12 },
  { key: 'time', label: 'Time', width: 14 },
  { key: 'place', label: 'Location', width: 26 },
  { key: 'scope', label: 'Scope', width: 10 },
  { key: 'module_name', label: 'Module', width: 26 },
  { key: 'inspection_type_name', label: 'Type', width: 26 },
  { key: 'inspector_name', label: 'Inspecting officer', width: 28 },
  { key: 'joint_with', label: 'Accompanied by', width: 28 },
  { key: 'areas_on_sheet', label: 'Areas on sheet', width: 12 },
  { key: 'areas_covered', label: 'Attended to', width: 11 },
  { key: 'areas_satisfactory', label: 'In order', width: 10 },
  { key: 'areas_with_deficiencies', label: 'With deficiencies', width: 14 },
  { key: 'areas_not_inspected', label: 'Not inspected', width: 12 },
  { key: 'coverage_pct', label: 'Coverage %', width: 11 },
  { key: 'items_checked', label: 'Items checked', width: 12 },
  { key: 'items_ok', label: 'Items in order', width: 12 },
  { key: 'observation_count', label: 'Deficiencies', width: 12 },
  { key: 'open_count', label: 'Open', width: 8 },
  { key: 'overdue_count', label: 'Overdue', width: 9 },
  { key: 'closed_count', label: 'Closed', width: 9 },
  { key: 'previous_ref_no', label: 'Previous inspection', width: 18 },
  { key: 'report_status', label: 'Report', width: 10 },
  { key: 'status', label: 'Status', width: 12 },
];

const INSPECTOR_COLUMNS = [
  { key: 'inspector_name', label: 'Inspecting officer', width: 30 },
  { key: 'inspector_designation', label: 'Designation', width: 28 },
  { key: 'inspections', label: 'Inspections', width: 11 },
  { key: 'stations_covered', label: 'Locations', width: 10 },
  { key: 'areas_covered', label: 'Areas attended to', width: 15 },
  { key: 'areas_satisfactory', label: 'Areas in order', width: 13 },
  { key: 'items_checked', label: 'Items checked', width: 12 },
  { key: 'avg_coverage_pct', label: 'Avg coverage %', width: 13 },
  { key: 'observations', label: 'Deficiencies raised', width: 16 },
  { key: 'avg_observations', label: 'Per inspection', width: 13 },
  { key: 'open', label: 'Open', width: 8 },
  { key: 'overdue', label: 'Overdue', width: 9 },
  { key: 'closed', label: 'Closed', width: 9 },
  { key: 'closure_pct', label: 'Closure %', width: 10 },
  { key: 'reports_issued', label: 'Reports issued', width: 12 },
  { key: 'last_inspection', label: 'Last inspection', width: 13 },
];

/** Builds the WHERE clause for an inspection-based report. */
function inspectionWhere(filters, user) {
  const where = ['1=1'];
  const params = [];
  const eq = (col, value) => {
    if (value === undefined || value === null) return;
    where.push(`i.${col} = ?`);
    params.push(value);
  };
  eq('module_id', filters.module_id);
  eq('station_id', filters.station_id);
  eq('inspector_id', filters.inspector_id);
  if (filters.module_code) {
    where.push('i.module_code = ?');
    params.push(filters.module_code);
  }
  if (filters.division_id) {
    where.push('i.station_id IN (SELECT id FROM stations WHERE division_id = ?)');
    params.push(filters.division_id);
  }
  if (filters.scope) {
    where.push('i.scope = ?');
    params.push(filters.scope);
  }
  if (filters.status) {
    const list = filters.status.split(',').map((x) => x.trim()).filter(Boolean);
    where.push(`i.status IN (${list.map(() => '?').join(',')})`);
    params.push(...list);
  }
  if (filters.mine) {
    where.push('i.inspector_id = ?');
    params.push(user.id);
  }
  const from = filters.from ?? (filters.days ? `-${filters.days} days` : null);
  if (filters.days && !filters.from) {
    where.push("date(COALESCE(i.started_at, i.created_at)) >= date('now', 'localtime', ?)");
    params.push(from);
  } else if (filters.from) {
    where.push('date(COALESCE(i.started_at, i.created_at)) >= date(?)');
    params.push(filters.from);
  }
  if (filters.to) {
    where.push('date(COALESCE(i.started_at, i.created_at)) <= date(?)');
    params.push(filters.to);
  }
  if (filters.q) {
    const like = `%${filters.q.toLowerCase()}%`;
    where.push(
      `(lower(i.ref_no) LIKE ? OR lower(COALESCE(i.inspection_no,'')) LIKE ?
        OR lower(COALESCE(i.title,'')) LIKE ? OR lower(COALESCE(i.station_name,'')) LIKE ?
        OR lower(COALESCE(i.station_code,'')) LIKE ? OR lower(i.inspector_name) LIKE ?)`
    );
    params.push(like, like, like, like, like, like);
  }
  const scope = inspectionScopeClause(user, { table: 'i' });
  if (scope.sql !== '1=1') {
    where.push(scope.sql);
    params.push(...scope.params);
  }
  return { sql: where.join(' AND '), params };
}

/** One row per inspection, with its coverage and its deficiency counters. */
function fetchInspections(filters, user) {
  const { sql, params } = inspectionWhere(filters, user);
  return all(
    `SELECT i.*,
            (SELECT COUNT(*) FROM v_observations o
              WHERE o.inspection_id = i.id AND o.is_overdue = 1) AS overdue_count
       FROM v_inspections i WHERE ${sql}
      ORDER BY COALESCE(i.started_at, i.created_at) DESC, i.id DESC LIMIT ?`,
    [...params, filters.limit ?? 1000]
  ).map((row) => ({
    ...row,
    date: String(row.started_at ?? row.created_at ?? '').slice(0, 10),
    time: row.from_time ? `${row.from_time}${row.to_time ? `-${row.to_time}` : ''}` : '',
    place:
      row.station_name
        ? `${row.station_name} (${row.station_code})`
        : row.train_number
          ? `${row.train_number} ${row.train_name ?? ''}`.trim()
          : row.section ?? '-',
  }));
}

const inspectionFilterSchema = filterSchema.extend({
  inspector_id: optionalId,
  scope: z.enum(['station', 'train', 'section']).optional(),
});

/**
 * The inspection register: what inspection work was done, one row per visit. This
 * is the report the division reads to see whether the inspections are happening,
 * which no observation-wise report can answer.
 */
router.get(
  '/inspection-register',
  query(inspectionFilterSchema),
  asyncRoute(async (req, res) => {
    const rows = fetchInspections(req.validQuery, req.user);
    const totals = registerTotals(rows);
    await deliverInspections(req, res, {
      rows,
      totals,
      columns: INSPECTION_COLUMNS,
      key: 'inspection-register',
      title: 'Inspection Register',
      subtitle: 'One row per inspection: the areas attended to, the items checked and the deficiencies raised',
      sheetName: 'Inspections',
    });
  })
);

/** Totals for the register, which are per-inspection sums rather than averages. */
function registerTotals(rows) {
  const sum = (key) => rows.reduce((n, r) => n + (Number(r[key]) || 0), 0);
  const covered = sum('areas_covered');
  const onSheet = sum('areas_on_sheet') - sum('areas_not_available');
  return [
    { metric: 'Inspections', value: rows.length },
    { metric: 'Locations inspected', value: new Set(rows.map((r) => r.place)).size },
    { metric: 'Inspecting officers', value: new Set(rows.map((r) => r.inspector_name)).size },
    { metric: 'Areas attended to', value: covered },
    { metric: 'Areas found in order', value: sum('areas_satisfactory') },
    { metric: 'Areas with deficiencies', value: sum('areas_with_deficiencies') },
    { metric: 'Areas not inspected', value: sum('areas_not_inspected') },
    { metric: 'Average coverage', value: onSheet ? `${Math.round((covered / onSheet) * 100)}%` : '-' },
    { metric: 'Items checked', value: sum('items_checked') },
    { metric: 'Items found in order', value: sum('items_ok') },
    { metric: 'Deficiencies raised', value: sum('observation_count') },
    {
      metric: 'Deficiencies per inspection',
      value: rows.length ? (sum('observation_count') / rows.length).toFixed(1) : '-',
    },
    { metric: 'Still open', value: sum('open_count') },
    { metric: 'Overdue', value: sum('overdue_count') },
    { metric: 'Reports issued', value: rows.filter((r) => r.report_status === 'issued').length },
  ];
}

/**
 * Inspector-wise: the same inspections summed by the officer who carried them out,
 * so the division can see who is inspecting, how much of each station they cover,
 * and whether what they raise gets closed.
 */
router.get(
  '/inspector-wise',
  query(inspectionFilterSchema),
  asyncRoute(async (req, res) => {
    const inspections = fetchInspections({ ...req.validQuery, limit: 5000 }, req.user);
    const by = new Map();
    for (const i of inspections) {
      const key = i.inspector_id;
      if (!by.has(key)) {
        by.set(key, {
          inspector_id: key,
          inspector_name: i.inspector_name,
          inspector_designation: i.inspector_designation ?? '',
          inspections: 0,
          locations: new Set(),
          areas_on_sheet: 0,
          areas_available: 0,
          areas_covered: 0,
          areas_satisfactory: 0,
          items_checked: 0,
          observations: 0,
          open: 0,
          overdue: 0,
          closed: 0,
          reports_issued: 0,
          last_inspection: '',
        });
      }
      const row = by.get(key);
      row.inspections += 1;
      row.locations.add(i.place);
      row.areas_on_sheet += i.areas_on_sheet ?? 0;
      row.areas_available += (i.areas_on_sheet ?? 0) - (i.areas_not_available ?? 0);
      row.areas_covered += i.areas_covered ?? 0;
      row.areas_satisfactory += i.areas_satisfactory ?? 0;
      row.items_checked += i.items_checked ?? 0;
      row.observations += i.observation_count ?? 0;
      row.open += i.open_count ?? 0;
      row.overdue += i.overdue_count ?? 0;
      row.closed += i.closed_count ?? 0;
      if (i.report_status === 'issued') row.reports_issued += 1;
      if (i.date > row.last_inspection) row.last_inspection = i.date;
    }
    const rows = [...by.values()]
      .map((r) => ({
        ...r,
        stations_covered: r.locations.size,
        avg_coverage_pct: r.areas_available ? Math.round((r.areas_covered / r.areas_available) * 100) : null,
        avg_observations: r.inspections ? Number((r.observations / r.inspections).toFixed(1)) : 0,
        closure_pct: r.observations ? Math.round((r.closed / r.observations) * 100) : null,
      }))
      .sort((a, b) => b.inspections - a.inspections || b.areas_covered - a.areas_covered);

    await deliverInspections(req, res, {
      rows,
      totals: [
        { metric: 'Inspecting officers', value: rows.length },
        { metric: 'Inspections', value: inspections.length },
        { metric: 'Areas attended to', value: rows.reduce((n, r) => n + r.areas_covered, 0) },
        { metric: 'Items checked', value: rows.reduce((n, r) => n + r.items_checked, 0) },
        { metric: 'Deficiencies raised', value: rows.reduce((n, r) => n + r.observations, 0) },
        {
          metric: 'Inspections per officer',
          value: rows.length ? (inspections.length / rows.length).toFixed(1) : '-',
        },
      ],
      columns: INSPECTOR_COLUMNS,
      key: 'inspector-wise',
      title: 'Inspector-wise Report',
      subtitle: 'Inspection work by the officer who carried it out',
      sheetName: 'Inspectors',
    });
  })
);

/** Renders an inspection-based report in whichever format was asked for. */
async function deliverInspections(req, res, { rows, totals, columns, key, title, subtitle, sheetName }) {
  const { format } = req.validQuery;
  if (format === 'json') {
    res.json({ data: rows, summary: totals, count: rows.length });
    return;
  }
  if (format === 'csv') {
    download(res, { fileName: `${key}.csv`, contentType: 'text/csv; charset=utf-8' });
    res.send(toCsv(rows, columns));
    return;
  }
  if (format === 'xlsx') {
    const buffer = await toXlsx([
      { name: sheetName, title, subtitle, columns, rows },
      {
        name: 'Summary',
        title: `${title} - summary`,
        columns: [
          { key: 'metric', label: 'Metric', width: 34 },
          { key: 'value', label: 'Value', width: 16 },
        ],
        rows: totals,
      },
    ]);
    download(res, {
      fileName: `${key}.xlsx`,
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    res.send(buffer);
    return;
  }
  const verification = reportToken(req, { reportType: key, params: req.validQuery });
  // The PDF carries the columns a reader can take in; the full set is in the
  // spreadsheet, which is what a wide table is for.
  const printed = columns.filter((c) => !PDF_SKIP[key]?.includes(c.key));
  const share = 1 / printed.length;
  streamPdf(
    res,
    {
      fileName: `${key}.pdf`,
      title,
      subtitle,
      meta: [
        { label: 'Generated', value: new Date().toISOString().slice(0, 19).replace('T', ' ') },
        { label: 'Rows', value: rows.length },
      ],
      verifyUrl: verification.url,
    },
    (doc, helpers) => {
      helpers.table(
        doc,
        printed.map((c) => ({ label: c.label, key: c.key, width: share })),
        rows,
        { fontSize: 7 }
      );
      doc.moveDown(0.3);
      doc.font('Helvetica-Bold').fontSize(9).text('Summary');
      doc.font('Helvetica').fontSize(8.5);
      for (const row of totals) doc.text(`${row.metric}: ${row.value}`);
    }
  );
}

/** Columns left out of the PDF, which has to stay readable on one page width. */
const PDF_SKIP = {
  'inspection-register': [
    'ref_no', 'scope', 'joint_with', 'items_ok', 'areas_not_inspected',
    'previous_ref_no', 'status', 'module_name',
  ],
  'inspector-wise': ['inspector_designation', 'areas_satisfactory', 'reports_issued'],
};

/* --------------------------- raw observation export ---------------------- */

router.get('/observations', query(filterSchema), asyncRoute((req, res) =>
  respondWithObservations(req, res, {
    title: 'Observation Register',
    subtitle: 'Filtered observation export',
    filters: req.validQuery,
    reportType: 'observations',
  })
));

/* ----------------------------- audit trail export ------------------------ */

router.get(
  '/audit',
  query(
    z.object({
      format: z.enum(['json', 'csv', 'xlsx']).default('json'),
      entity_type: optionalText,
      entity_id: optionalText,
      user_id: optionalId,
      action: optionalText,
      from: optionalIsoDate,
      to: optionalIsoDate,
      limit: z.coerce.number().int().min(1).max(5000).default(500),
    })
  ),
  asyncRoute(async (req, res) => {
    if (!['admin', 'divisional_officer'].includes(req.user.role)) {
      throw badRequest('Only an administrator or divisional officer can export the audit trail');
    }
    const f = req.validQuery;
    const where = ['1=1'];
    const params = [];
    for (const [col, val] of [
      ['entity_type', f.entity_type],
      ['entity_id', f.entity_id],
      ['user_id', f.user_id],
      ['action', f.action],
    ]) {
      if (val !== undefined) {
        where.push(`${col} = ?`);
        params.push(val);
      }
    }
    if (f.from) {
      where.push('date(created_at) >= date(?)');
      params.push(f.from);
    }
    if (f.to) {
      where.push('date(created_at) <= date(?)');
      params.push(f.to);
    }
    const rows = all(
      `SELECT id, created_at, user_name, role, action, entity_type, entity_id, remarks,
              previous_value, new_value, ip
         FROM audit_log WHERE ${where.join(' AND ')} ORDER BY id DESC LIMIT ?`,
      [...params, f.limit]
    );
    const columns = [
      { key: 'created_at', label: 'Timestamp', width: 22 },
      { key: 'user_name', label: 'User', width: 22 },
      { key: 'role', label: 'Role', width: 16 },
      { key: 'action', label: 'Action', width: 24 },
      { key: 'entity_type', label: 'Entity', width: 14 },
      { key: 'entity_id', label: 'Entity ID', width: 12 },
      { key: 'remarks', label: 'Remarks', width: 40 },
      { key: 'previous_value', label: 'Previous value', width: 50 },
      { key: 'new_value', label: 'New value', width: 50 },
      { key: 'ip', label: 'IP', width: 14 },
    ];
    await respondWithTable(req, res, {
      title: 'Audit Trail',
      subtitle: 'User, date, time, action, previous value and new value',
      reportType: 'audit',
      columns,
      rows,
      format: f.format,
    });
  })
);

export default router;
